# Generated by Django 4.1.7 on 2023-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
